spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/onestop'
    username: bibhu04
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


# spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898