
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/onestop-invoice'
    username: bibhu04
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bibhupattanaik04@gmail.com
    password: gkyw yhmy zyne wobm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# spring:
  application:
    name: ONESTOP-INVOICE

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        hystrix:
          enabled: true
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 1000


management:
  endpoints:
    web:
      exposure:
        include: '*'
