spring:
  cloud:
    gateway:
      routes:
        - id: ott-invoice
          uri: ib://OTT-INVOICE
          predicates:
          - Path=/invoice/generate-invoice
          
        - id: ott-stub
          uri: lb://OTT-STUB
          predicates:
          - Path=/ott/**
          
        - id: onestop=billing-app
          uri: lb://ONESTOP-BILLING
          predicates:
           - Path=/subscribe/plan
        
        - id: onestop=billing-app
          uri: lb://ONESTOP-BILLING
          predicates:
           - Path=/subscribe/create-invoice

        - id: onestop-app-app
          uri: lb://ONESTOP-APP
          predicates:
            - Path=/app/home

        - id: onestop-app-app
          uri: lb://ONESTOP-APP
          predicates:
            - Path=/app/invoice-details


        - id: onestop-app-app
          uri: lb://ONESTOP-APP
          predicates:
            - Path=/app/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              -  "http://localhost:4200" 
              -  "http://localhost:4200/login"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

  application:
    name: ONESTOP-GATEWAY

# server:
#   servlet:
#     context-path: /employee-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
