spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/onestop-auth'
    username: bibhu04
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

