
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/onestop-billing'
    username: bibhu04
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# spring:
  application:
    name: ONESTOP-BILLING

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        hystrix:
          enabled: true
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 1000


management:
  endpoints:
    web:
      exposure:
        include: '*'